parameters:
    number_of_names: 5
    maximum_name_length: 5
    n_grams:
        - 1
        - 2

training_words:
    - I
    - like
    - toasted
    - cheese
    - sandwiches

# Optional
godaddy:
    key: <your key>
    secret: <your secret>
    env: OTE | PROD

extensions:
    - .info
    - .dev
    - .ai
