godaddy-prod:
    key: <your key>
    secret: <your secret>

parameters:
    number_of_names: 1
    maximum_name_length: 2
    n_grams:
        - 1
        - 2
        
extensions:
    - .info
    - .dev
    - .ai

training_words:
    - I
    - like
    - toasted
    - cheese
    - sandwiches
